name: CI (Build + Test)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 🔨 Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: Create env file
        run: mv .env.example .env

      - name: 🔎 Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  #    - name: ⚙ Integration Tests
  #      uses: actions-rs/cargo@v1
  #      with:
  #        command: test
  #        args: --features "integration_tests"